// buttons-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'buttons-angular';
}

<header>
  Buttons
</header>
<main>
  <div>
    <app-button></app-button>
  </div>
  <div>
    <app-button variant='outline'></app-button>
  </div>
  <div>
    <app-button variant='text'></app-button>
  </div>
  <div>
    <app-button [disableShadow]='true'></app-button>
  </div>
  <div>
    <app-button [disabled]='true'></app-button>
    <app-button variant='text' [disabled]='true'></app-button>
  </div>
  <div>
    <app-button startIcon='local_grocery_store'></app-button>
    <app-button endIcon='local_grocery_store'></app-button>
  </div>
  <div>
    <app-button size='sm'></app-button>
    <app-button size='md'></app-button>
    <app-button size='lg'></app-button>
  </div>
  <div>
    <app-button color='default'></app-button>
    <app-button color='primary'></app-button>
    <app-button color='secondary'>Secondary</app-button>
    <app-button color='danger'>Danger</app-button>
  </div>
  <div class='icons-text'>
    Icons: htpps://material.io/resources/icons/?style=round
  </div>
</main>
<footer>
  created by
  <span class='username'>
    username
  </span>
  - devchallenges.io
</footer>

// buttons-react/src/app/App.tsx
import './App.scss'
import Button from './components/Button'

function App() {
  return (
    <div className="App">
      <header>Buttons</header>
      <main>
        <div>
          <Button label="Default" />
        </div>
        <div>
          <Button variant="outline" label="Default" />
        </div>
        <div>
          <Button variant="text" label="Default"></Button>
        </div>
        <div>
          <Button disableShadow={true} label="Default"></Button>
        </div>
        <div>
          <Button disabled={true} label="Default"></Button>
          <Button variant="text" disabled={true} label="Default"></Button>
        </div>
        <div>
          <Button startIcon="local_grocery_store" label="Default"></Button>
          <Button endIcon="local_grocery_store" label="Default"></Button>
        </div>
        <div>
          <Button size="sm" label="Default"></Button>
          <Button size="md" label="Default"></Button>
          <Button size="lg" label="Default"></Button>
        </div>
        <div>
          <Button color="default" label="Default"></Button>
          <Button label="Primary" color="primary" ></Button>
          <Button label="Secondary" color="secondary" />
          <Button label="Danger" color="danger" />
        </div>
        <div className="icons-text">
          Icons: htpps://material.io/resources/icons/?style=round
        </div>
      </main>
      <footer>
        created by
        <span className="username">username</span>- devchallenges.io
      </footer>
    </div>
  )
}

export default App
