// buttons-react/src/app/components/Button/index.tsx
import { ButtonProps } from '../props';
import './index.scss';
export default function Button({
  label,
  startIcon = null,
  endIcon = null,
  variant = 'default',
  color = 'primary',
  size = 'md',
  disabled = false,
  disableShadow = false,
  ...props
}: ButtonProps) {
  return (
    <button
      disabled={disabled}
      color={color}
      className={[
        startIcon && 'startIcon',
        endIcon && 'endIcon',
        disableShadow && 'disabledShadow',
        `variant-${variant}`,
        `size-${size}`,
      ].join(' ')}
    >
      {startIcon && <i className="material-icons">{startIcon}</i>}
      {label}
      {endIcon && <i className="material-icons">{endIcon}</i>}
    </button>
  )
}

// buttons-angular/src/app/components/button/button.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-button',
  template: `
    <button
      [attr.variant]="variant"
      [attr.size]="size"
      [attr.color]="color"
      [attr.startIcon]="startIcon.length > 0 ? startIcon : undefined"
      [attr.endIcon]="endIcon.length > 0 ? endIcon : undefined"
      [attr.disabled]="disabled ? 'disabled' : undefined"
      [attr.disableShadow]="disableShadow ? 'disabledShadow' : undefined"
    >
      <i *ngIf="startIcon.length > 0" class="material-icons">
        {{ startIcon }}
      </i>
      {{ label }}
      <i *ngIf="endIcon.length > 0" class="material-icons">
        {{ endIcon }}
      </i>
    </button>
  `,
  styleUrls: ['./button.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ButtonComponent implements OnInit {
  @Input() label = 'Default';

  @Input() startIcon: string = '';
  @Input() endIcon: string = '';
  @Input() variant: 'default' | 'outline' | 'text' = 'default';
  @Input() color: 'default' | 'primary' | 'secondary' | 'danger' = 'default';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';

  @Input() disabled: boolean = false;
  @Input() disableShadow: boolean = false;
  constructor() {}

  ngOnInit(): void {
    if (this.startIcon != '' || (this.endIcon != '' && this.color == 'default'))
      this.color = 'primary';
    if (
      this.disableShadow == true &&
      this.color == 'default' &&
      this.variant == 'default' &&
      this.startIcon == '' &&
      this.endIcon == ''
    )
      this.color = 'primary';
  }
}
